/* 
cemal ünal 16070006087  
olcay türkdoğan 16070006097

A slot machine simulation.If the same colomns match ,You win an award
and background of the same columns turns red.

*/



package slotmachine;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;


public final class Slot extends javax.swing.JFrame {

    private int credit = 100, bet = 15, win, lost;
    private final int  creditPurchase = 100;
    private double prize = 25.0,  source;
    private final double creditSell = 10.0;
    private int reels1, reels2, reels3;
    private ArrayList<ImageIcon> images = new ArrayList<ImageIcon>();
    private final DecimalFormat df = new DecimalFormat("0.00");

    public Slot(int credits, int bet, double payout, int reel1, int reel2, int reel3) {
        this.credit = credits;
        this.bet = bet;
        this.prize = payout;
        this.reels1 = reel1;
        this.reels2 = reel2;
        this.reels3 = reel3;
        loadImages();

    }

    public Slot() {
        initComponents();
        loadImages();
        jTextField3.setText(" " + credit);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Jackpot");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jPanel5.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel5.setLayout(null);

        jButton2.setText("More credits");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(440, 360, 130, 100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Money  :");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(70, 460, 160, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Credits  :");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(70, 430, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Loss       :");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(70, 400, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Win        :");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(70, 350, 100, 60);

        jTextField1.setEditable(false);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(190, 370, 45, 22);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(190, 400, 45, 22);

        jTextField3.setEditable(false);
        jTextField3.setRequestFocusEnabled(false);
        jPanel5.add(jTextField3);
        jTextField3.setBounds(190, 440, 40, 22);

        jTextField4.setEditable(false);
        jTextField4.setToolTipText("");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4);
        jTextField4.setBounds(190, 480, 50, 22);

        jButton1.setText("Spinn!!!!");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(100, 220, 375, 34);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 170));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachine/images/Seven.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachine/images/Seven.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachine/images/Seven.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel1);
        jPanel1.setBounds(40, 40, 486, 170);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachine/images/bg.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, 0, 600, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (source >= creditSell) {
            source -= creditSell;
            jTextField4.setText(" " + df.format(source));
            credit += creditPurchase;
            jTextField3.setText(" " + credit);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((credit - bet) >= 0) {
            jPanel2.setBackground(new java.awt.Color(240, 240, 240)); // Highlights matched icons.
            jPanel3.setBackground(new java.awt.Color(240, 240, 240));
            jPanel4.setBackground(new java.awt.Color(240, 240, 240));
            genRand();
            matchControl();
        } else {
            jTextField3.setText("***");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    
    /* Generates 3 random numbers */
    public void genRand() {

        Random rand = new Random();

        reels1 = rand.nextInt(images.size());
        reels2 = rand.nextInt(images.size());
        reels3 = rand.nextInt(images.size());

        setReels(reels1, reels2, reels3); // Set the reel image
    }

    /* Sets the reels in images ArrayList. */
    public void setReels(int ico1, int ico2, int ico3) {
        jLabel4.setIcon(images.get(ico1));
        jLabel5.setIcon(images.get(ico2));
        jLabel6.setIcon(images.get(ico3));
    }

    /*Player change money to credit */
    public void buyCredits() {
        if (source >= creditSell) {
            source -= creditSell;
            jTextField4.setText(" " + df.format(source));
            credit += creditPurchase;
            jTextField3.setText(" " + credit);

        }

    }

    /*  Calculate prizes */
    public double getPrize(double prize) {
        if (reels1 == reels2 && reels2 == reels3) {

            prize = this.prize; 
        } else if (reels1 == reels2 || reels1 == reels3 || reels2 == reels3) {

            prize = this.prize / 5; // if two are matched 
        } else {
            prize = 0; // If no win
        }
        return prize;
    }

    
    /* Loads ImageIcons into the images ArrayList. */
    public void loadImages() {
        images.add(createImageIcon("images/Banana.png", "Banana"));
        images.add(createImageIcon("images/Bar.png", "Bar"));
        images.add(createImageIcon("images/Bell.png", "Bell"));
        images.add(createImageIcon("images/Cherry.png", "Cherry"));
        images.add(createImageIcon("images/Clover.png", "Clover"));
        images.add(createImageIcon("images/Diamond.png", "Diamond"));
        images.add(createImageIcon("images/Plum.png", "Plum"));
        images.add(createImageIcon("images/Seven.png", "Seven"));
        images.add(createImageIcon("images/Watermelon.png", "Watermelon"));
    }

    /* Create a new ImageIcon */
    public ImageIcon createImageIcon(String path, String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    public void matchControl() {
        if (reels1 == reels2 && reels2 == reels3) {

            jPanel2.setBackground(Color.red); // Highlights matched icons.
            jPanel3.setBackground(Color.red);
            jPanel4.setBackground(Color.red);
            jTextField3.setText(" " + (credit -= bet)); 
            jTextField4.setText(" " + df.format((source += getPrize(prize)))); // If there is a win add amount to cash pot.
            jTextField1.setText(" " + win()); // increment win amount.
        } else if (reels1 == reels2 || reels1 == reels3) {
            jTextField3.setText(" " + (credit -= bet));
            jTextField4.setText(" " + df.format((source += getPrize(prize))));
            jTextField1.setText(" " + win());

            if (reels1 == reels2) {
                jPanel2.setBackground(Color.red);
                jPanel3.setBackground(Color.red);
            } else if (reels1 == reels3) {
                jPanel2.setBackground(Color.red);
                jPanel4.setBackground(Color.red);
            }
        } else if (reels2 == reels3) {
            jPanel3.setBackground(Color.red);
            jPanel4.setBackground(Color.red);
            jTextField3.setText(" " + (credit -= bet));
            jTextField4.setText(" " + df.format((source += getPrize(prize))));
            jTextField1.setText(" " + win());
        } else {

            jTextField2.setText(" " + lose());
            jTextField3.setText(" " + (credit -= bet));
        }

    }

    public int lose() {
        lost++;
        return lost;
    }

    public int win() {
        win++;

        return win;
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Slot().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
